/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void gtl__draw(void);

static void gtl__draw(void)
{
    md_cls(1);
    md_print("hello genesis", 116, 32, 14);
    md_circfill(128, 80, 44, 10);
    md_rectfill(112, 60, 120, 74, 0);
    md_rectfill(136, 60, 144, 74, 0);
    md_circfill(128, 98, 13, 0);
}

int main(bool hard)
{
    (void)hard;
    md_init();
    for (;;) {
        md_vsync();
        gtl__draw();
        md_endframe();
    }
    return 0;
}
