/* generated by mdlua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void gtl__init(void);
static void gtl__update60(void);
static void gtl__draw(void);

int gtl_song = 0;
int gtl_playing = 1;

static void gtl__init(void)
{
    md_music(gtl_song, 1);
}

static void gtl__update60(void)
{
    if (md_btnp(4, 0)) {
        gtl_song = (gtl_song + 1);
        if ((gtl_song > 1)) {
            gtl_song = 0;
        }
        md_music(gtl_song, 1);
        gtl_playing = 1;
    }
    if (md_btnp(5, 0)) {
        if ((gtl_playing == 1)) {
            gtl_playing = 0;
            md_music((-1), 1);
        } else {
            gtl_playing = 1;
            md_music(gtl_song, 1);
        }
    }
    if (md_btnp(7, 0)) {
        md_sfx(0, -1);
    }
}

static void gtl__draw(void)
{
    md_cls(1);
    md_print("music bank", 8, 8, 7);
    md_print("song:", 8, 28, 6);
    md_print_int(gtl_song, 48, 28, 11);
    if ((gtl_playing == 1)) {
        md_print("playing", 8, 40, 11);
    } else {
        md_print("stopped", 8, 40, 8);
    }
    md_print("O next  X stop  START sfx", 8, 60, 5);
}

int main(bool hard)
{
    (void)hard;
    md_init();
    gtl__init();
    for (;;) {
        md_vsync();
        gtl__update60();
        gtl__draw();
        md_endframe();
    }
    return 0;
}
