/* generated by mdlua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_x = 60;
int lcl_y = 60;
int lcl_dx = 1;
int lcl_dy = 1;

static void lcl__init(void)
{
}

static void lcl__update60(void)
{
    lcl_x = (lcl_x + lcl_dx);
    lcl_y = (lcl_y + lcl_dy);
    if (((lcl_x < 4) || (lcl_x > 300))) {
        lcl_dx = (-lcl_dx);
    }
    if (((lcl_y < 20) || (lcl_y > 200))) {
        lcl_dy = (-lcl_dy);
    }
}

static void lcl__draw(void)
{
    md_cls(1);
    md_print("parity", 8, 8, 7);
    md_spr(0, lcl_x, lcl_y, 2, 2, 0 | (0 << 1));
}

int main(bool hard)
{
    (void)hard;
    md_init();
    lcl__init();
    for (;;) {
        md_vsync();
        lcl__update60();
        lcl__draw();
        md_endframe();
    }
    return 0;
}
