/* generated by mdlua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static int gtl_nextcolor(void);
static int gtl_canplace(void);
static void gtl_spawn(void);
static int gtl_scanmatches(void);
static void gtl_applygravity(void);
static int gtl_resolve(void);
static void gtl_lockpiece(void);
static void gtl_newgame(void);
static void gtl_clearplane(void);
static void gtl_paintframe(void);
static void gtl__init(void);
static void gtl__update60(void);
static void gtl_paintboard(void);
static void gtl__draw(void);

int gtl_GW = 6;
int gtl_GH = 12;
int gtl_ITX = 14;
int gtl_ITY = 3;
int gtl_T_EMPTY = 0;
int gtl_T_WELL = 1;
int gtl_T_FRAME = 2;
int gtl_T_GEM0 = 3;
unsigned char gtl_grid[72];
unsigned char gtl_mask[72];
int gtl_px = 3;
int gtl_py = 0;
int gtl_c1 = 1;
int gtl_c2 = 2;
int gtl_c3 = 3;
int gtl_score = 0;
int gtl_level = 1;
int gtl_cleared = 0;
int gtl_fallt = 0;
int gtl_state = 0;
int gtl_flasht = 0;
int gtl_dirty = 1;
int gtl_seed = 137;
int gtl_qcol = 0;
int gtl_qrow = 0;

static int gtl_nextcolor(void)
{
    gtl_seed = ((((((gtl_seed) << 3) + ((gtl_seed) << 2) + (gtl_seed)) + 7)) % (251));
    return (((gtl_seed) % (5)) + 1);
}

static int gtl_canplace(void)
{
    if ((gtl_qcol < 0)) {
        return 0;
    }
    if (((gtl_qcol - (gtl_GW)) >= 0)) {
        return 0;
    }
    { unsigned char gtl_i = 0; unsigned char L_lim0 = 2;
        for (; gtl_i <= L_lim0; ++gtl_i) {
            { int gtl_ry = (gtl_qrow + gtl_i);
                if (((gtl_ry - (gtl_GH)) >= 0)) {
                    return 0;
                }
                if ((gtl_ry >= 0)) {
                    if (((unsigned char)gtl_grid[((gtl_ry * gtl_GW) + gtl_qcol)] != (unsigned char)0)) {
                        return 0;
                    }
                }
            }
        }
    }
    return 1;
}

static void gtl_spawn(void)
{
    gtl_px = 3;
    gtl_py = (-2);
    gtl_c1 = gtl_nextcolor();
    gtl_c2 = gtl_nextcolor();
    gtl_c3 = gtl_nextcolor();
    gtl_qcol = gtl_px;
    gtl_qrow = 0;
    if ((gtl_canplace() == 0)) {
        gtl_state = 1;
        md_music((-1), 1);
    }
}

static int gtl_scanmatches(void)
{
    { int gtl_i = 1; int L_lim1 = (gtl_GW * gtl_GH);
        for (; gtl_i <= L_lim1; ++gtl_i) {
            gtl_mask[gtl_i - 1] = 0;
        }
    }
    { int gtl_count = 0;
        { int gtl_row = 0; int L_lim2 = (gtl_GH - 1);
            for (; gtl_row <= L_lim2; ++gtl_row) {
                { int gtl_col = 0; int L_lim3 = (gtl_GW - 1);
                    for (; gtl_col <= L_lim3; ++gtl_col) {
                        { int gtl_v = gtl_grid[((gtl_row * gtl_GW) + gtl_col)];
                            if ((gtl_v != 0)) {
                                { unsigned char gtl_d = 0; unsigned char L_lim4 = 3;
                                    for (; gtl_d <= L_lim4; ++gtl_d) {
                                        { int gtl_dc = 0;
                                            { int gtl_dr = 0;
                                                if (((unsigned char)gtl_d == (unsigned char)0)) {
                                                    gtl_dc = 1;
                                                    gtl_dr = 0;
                                                }
                                                if (((unsigned char)gtl_d == (unsigned char)1)) {
                                                    gtl_dc = 0;
                                                    gtl_dr = 1;
                                                }
                                                if (((unsigned char)gtl_d == (unsigned char)2)) {
                                                    gtl_dc = 1;
                                                    gtl_dr = 1;
                                                }
                                                if (((unsigned char)gtl_d == (unsigned char)3)) {
                                                    gtl_dc = (-1);
                                                    gtl_dr = 1;
                                                }
                                                { int gtl_pc = (gtl_col - gtl_dc);
                                                    { int gtl_pr = (gtl_row - gtl_dr);
                                                        { int gtl_isstart = 1;
                                                            if (((((gtl_pc >= 0) && ((gtl_pc - (gtl_GW)) < 0)) && (gtl_pr >= 0)) && ((gtl_pr - (gtl_GH)) < 0))) {
                                                                if (((gtl_grid[((gtl_pr * gtl_GW) + gtl_pc)] - (gtl_v)) == 0)) {
                                                                    gtl_isstart = 0;
                                                                }
                                                            }
                                                            if ((gtl_isstart != 0)) {
                                                                { int gtl_len = 1;
                                                                    { int gtl_nc = (gtl_col + gtl_dc);
                                                                        { int gtl_nr = (gtl_row + gtl_dr);
                                                                            while ((((((gtl_nc >= 0) && ((gtl_nc - (gtl_GW)) < 0)) && (gtl_nr >= 0)) && ((gtl_nr - (gtl_GH)) < 0)) && ((gtl_grid[((gtl_nr * gtl_GW) + gtl_nc)] - (gtl_v)) == 0))) {
                                                                                gtl_len = (gtl_len + 1);
                                                                                gtl_nc = (gtl_nc + gtl_dc);
                                                                                gtl_nr = (gtl_nr + gtl_dr);
                                                                            }
                                                                            if ((gtl_len >= 3)) {
                                                                                { int gtl_mc = gtl_col;
                                                                                    { int gtl_mr = gtl_row;
                                                                                        { int gtl_k = 1; int L_lim5 = gtl_len;
                                                                                            for (; gtl_k <= L_lim5; ++gtl_k) {
                                                                                                { int gtl_idx = (((gtl_mr * gtl_GW) + gtl_mc) + 1);
                                                                                                    if (((unsigned char)gtl_mask[gtl_idx - 1] == (unsigned char)0)) {
                                                                                                        gtl_mask[gtl_idx - 1] = 1;
                                                                                                        gtl_count = (gtl_count + 1);
                                                                                                    }
                                                                                                    gtl_mc = (gtl_mc + gtl_dc);
                                                                                                    gtl_mr = (gtl_mr + gtl_dr);
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        return gtl_count;
    }
}

static void gtl_applygravity(void)
{
    { int gtl_col = 0; int L_lim6 = (gtl_GW - 1);
        for (; gtl_col <= L_lim6; ++gtl_col) {
            { int gtl_w = (gtl_GH - 1);
                { int gtl_row = (gtl_GH - 1); int L_lim7 = 0;
                    for (; gtl_row >= L_lim7; --gtl_row) {
                        { int gtl_v = gtl_grid[((gtl_row * gtl_GW) + gtl_col)];
                            if ((gtl_v != 0)) {
                                gtl_grid[((gtl_w * gtl_GW) + gtl_col)] = gtl_v;
                                gtl_w = (gtl_w - 1);
                            }
                        }
                    }
                }
                while ((gtl_w >= 0)) {
                    gtl_grid[((gtl_w * gtl_GW) + gtl_col)] = 0;
                    gtl_w = (gtl_w - 1);
                }
            }
        }
    }
}

static int gtl_resolve(void)
{
    { int gtl_chain = 0;
        { int gtl_n = gtl_scanmatches();
            while ((gtl_n > 0)) {
                gtl_chain = (gtl_chain + 1);
                { int gtl_i = 1; int L_lim8 = (gtl_GW * gtl_GH);
                    for (; gtl_i <= L_lim8; ++gtl_i) {
                        if (((unsigned char)gtl_mask[gtl_i - 1] != (unsigned char)0)) {
                            gtl_grid[gtl_i - 1] = 0;
                        }
                    }
                }
                { int gtl_amt = (((gtl_n) << 3) + ((gtl_n) << 1));
                    if ((gtl_chain > 1)) {
                        gtl_amt = (gtl_amt * gtl_chain);
                    }
                    gtl_score = (gtl_score + gtl_amt);
                    gtl_cleared = (gtl_cleared + gtl_n);
                    { int gtl_want = (((gtl_cleared) / (12)) + 1);
                        if ((gtl_want > 9)) {
                            gtl_want = 9;
                        }
                        gtl_level = gtl_want;
                        md_sfx((40 + (((gtl_chain) << 2))), -1);
                        gtl_applygravity();
                        gtl_n = gtl_scanmatches();
                    }
                }
            }
            return gtl_chain;
        }
    }
}

static void gtl_lockpiece(void)
{
    { unsigned char gtl_i = 0; unsigned char L_lim9 = 2;
        for (; gtl_i <= L_lim9; ++gtl_i) {
            { int gtl_ry = (gtl_py + gtl_i);
                { int gtl_col = 0;
                    if (((unsigned char)gtl_i == (unsigned char)0)) {
                        gtl_col = gtl_c1;
                    }
                    if (((unsigned char)gtl_i == (unsigned char)1)) {
                        gtl_col = gtl_c2;
                    }
                    if (((unsigned char)gtl_i == (unsigned char)2)) {
                        gtl_col = gtl_c3;
                    }
                    if ((gtl_ry >= 0)) {
                        gtl_grid[((gtl_ry * gtl_GW) + gtl_px)] = gtl_col;
                    }
                }
            }
        }
    }
    md_sfx(20, -1);
    gtl_dirty = 1;
    if ((gtl_py < 0)) {
        gtl_state = 1;
        md_music((-1), 1);
        return;
    }
    { int gtl_chain = gtl_resolve();
        if ((gtl_chain > 0)) {
            gtl_flasht = 8;
        }
        if ((gtl_state == 0)) {
            gtl_spawn();
        }
    }
}

static void gtl_newgame(void)
{
    { int gtl_i = 1; int L_lim10 = (gtl_GW * gtl_GH);
        for (; gtl_i <= L_lim10; ++gtl_i) {
            gtl_grid[gtl_i - 1] = 0;
        }
    }
    gtl_score = 0;
    gtl_level = 1;
    gtl_cleared = 0;
    gtl_fallt = 0;
    gtl_flasht = 0;
    gtl_state = 0;
    gtl_dirty = 1;
    gtl_spawn();
}

static void gtl_clearplane(void)
{
    { unsigned char gtl_r = 0; unsigned char L_lim11 = 27;
        for (; gtl_r <= L_lim11; ++gtl_r) {
            { unsigned char gtl_c = 0; unsigned char L_lim12 = 39;
                for (; gtl_c <= L_lim12; ++gtl_c) {
                    md_mset(0, gtl_c, gtl_r, gtl_T_EMPTY);
                }
            }
        }
    }
}

static void gtl_paintframe(void)
{
    { int gtl_x0 = (gtl_ITX - 1);
        { int gtl_x1 = (gtl_ITX + (((gtl_GW) << 1)));
            { int gtl_c = gtl_x0; int L_lim13 = gtl_x1;
                for (; gtl_c <= L_lim13; ++gtl_c) {
                    md_mset(0, gtl_c, (gtl_ITY - 1), gtl_T_FRAME);
                    md_mset(0, gtl_c, (gtl_ITY + (((gtl_GH) << 1))), gtl_T_FRAME);
                }
            }
            { int gtl_r = gtl_ITY; int L_lim14 = ((gtl_ITY + (((gtl_GH) << 1))) - 1);
                for (; gtl_r <= L_lim14; ++gtl_r) {
                    md_mset(0, (gtl_ITX - 1), gtl_r, gtl_T_FRAME);
                    md_mset(0, (gtl_ITX + (((gtl_GW) << 1))), gtl_r, gtl_T_FRAME);
                }
            }
        }
    }
}

static void gtl__init(void)
{
    md_map_show(0);
    md_music(0, 1);
    gtl_clearplane();
    gtl_paintframe();
    gtl_newgame();
}

static void gtl__update60(void)
{
    if ((gtl_state != 0)) {
        if (md_btnp(7, 0)) {
            md_music(0, 1);
            gtl_newgame();
        }
        return;
    }
    if ((gtl_flasht > 0)) {
        gtl_flasht = (gtl_flasht - 1);
    }
    gtl_qrow = gtl_py;
    if (md_btnp(0, 0)) {
        gtl_qcol = (gtl_px - 1);
        if ((gtl_canplace() != 0)) {
            gtl_px = (gtl_px - 1);
        }
    }
    if (md_btnp(1, 0)) {
        gtl_qcol = (gtl_px + 1);
        if ((gtl_canplace() != 0)) {
            gtl_px = (gtl_px + 1);
        }
    }
    if (md_btnp(4, 0)) {
        { int gtl_t = gtl_c3;
            gtl_c3 = gtl_c2;
            gtl_c2 = gtl_c1;
            gtl_c1 = gtl_t;
            md_sfx(30, -1);
        }
    }
    if (md_btnp(5, 0)) {
        gtl_qcol = gtl_px;
        gtl_qrow = (gtl_py + 1);
        while ((gtl_canplace() != 0)) {
            gtl_py = (gtl_py + 1);
            gtl_qrow = (gtl_py + 1);
        }
        gtl_lockpiece();
        return;
    }
    if (md_btn(3, 0)) {
        gtl_fallt = (gtl_fallt + 4);
    }
    gtl_fallt = (gtl_fallt + 1);
    { int gtl_delay = (33 - (((gtl_level) << 1) + (gtl_level)));
        if (((gtl_fallt - (gtl_delay)) >= 0)) {
            gtl_fallt = 0;
            gtl_qcol = gtl_px;
            gtl_qrow = (gtl_py + 1);
            if ((gtl_canplace() != 0)) {
                gtl_py = (gtl_py + 1);
            } else {
                gtl_lockpiece();
            }
        }
    }
}

static void gtl_paintboard(void)
{
    { int gtl_blink = 0;
        if (((gtl_flasht > 0) && ((gtl_flasht & 1) == 0))) {
            gtl_blink = 1;
        }
        { int gtl_row = 0; int L_lim15 = (gtl_GH - 1);
            for (; gtl_row <= L_lim15; ++gtl_row) {
                { int gtl_col = 0; int L_lim16 = (gtl_GW - 1);
                    for (; gtl_col <= L_lim16; ++gtl_col) {
                        { int gtl_v = gtl_grid[((gtl_row * gtl_GW) + gtl_col)];
                            if ((((gtl_v != 0) && (gtl_blink != 0)) && ((unsigned char)gtl_mask[((gtl_row * gtl_GW) + gtl_col)] != (unsigned char)0))) {
                                gtl_v = 0;
                            }
                            { int gtl_tx = (gtl_ITX + (((gtl_col) << 1)));
                                { int gtl_ty = (gtl_ITY + (((gtl_row) << 1)));
                                    if ((gtl_v == 0)) {
                                        md_mset(0, gtl_tx, gtl_ty, gtl_T_WELL);
                                        md_mset(0, (gtl_tx + 1), gtl_ty, gtl_T_WELL);
                                        md_mset(0, gtl_tx, (gtl_ty + 1), gtl_T_WELL);
                                        md_mset(0, (gtl_tx + 1), (gtl_ty + 1), gtl_T_WELL);
                                    } else {
                                        { int gtl_base = (gtl_T_GEM0 + ((((gtl_v - 1)) << 2)));
                                            md_mset(0, gtl_tx, gtl_ty, gtl_base);
                                            md_mset(0, (gtl_tx + 1), gtl_ty, (gtl_base + 1));
                                            md_mset(0, gtl_tx, (gtl_ty + 1), (gtl_base + 2));
                                            md_mset(0, (gtl_tx + 1), (gtl_ty + 1), (gtl_base + 3));
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

static void gtl__draw(void)
{
    md_print("gem well", 8, 8, 11);
    md_print("score", 8, 40, 7);
    md_print_int(gtl_score, 8, 52, 10);
    md_print("level", 8, 80, 7);
    md_print_int(gtl_level, 8, 92, 9);
    md_print("O cycle", 8, 176, 6);
    md_print("X drop", 8, 188, 6);
    if ((gtl_state != 0)) {
        md_print("GAME OVER", 232, 96, 8);
        md_print("press", 240, 120, 7);
        md_print("START", 240, 132, 12);
    } else {
        md_print("         ", 232, 96, 7);
        md_print("     ", 240, 120, 7);
        md_print("     ", 240, 132, 7);
    }
    if (((gtl_dirty != 0) || (gtl_flasht > 0))) {
        gtl_paintboard();
        gtl_dirty = 0;
    }
    if ((gtl_state == 0)) {
        { unsigned char gtl_i = 0; unsigned char L_lim17 = 2;
            for (; gtl_i <= L_lim17; ++gtl_i) {
                { int gtl_ry = (gtl_py + gtl_i);
                    if ((gtl_ry >= 0)) {
                        { int gtl_col = 0;
                            if (((unsigned char)gtl_i == (unsigned char)0)) {
                                gtl_col = gtl_c1;
                            }
                            if (((unsigned char)gtl_i == (unsigned char)1)) {
                                gtl_col = gtl_c2;
                            }
                            if (((unsigned char)gtl_i == (unsigned char)2)) {
                                gtl_col = gtl_c3;
                            }
                            { int gtl_sx = ((((gtl_ITX + (((gtl_px) << 1)))) << 3));
                                { int gtl_sy = ((((gtl_ITY + (((gtl_ry) << 1)))) << 3));
                                    md_spr(((((gtl_col - 1)) << 1)), gtl_sx, gtl_sy, 2, 2, 0 | (0 << 1));
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

int main(bool hard)
{
    (void)hard;
    md_init();
    gtl__init();
    for (;;) {
        md_vsync();
        gtl__update60();
        gtl__draw();
        md_endframe();
    }
    return 0;
}
