/* generated by mdlua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static int lcl_nextcolor(void);
static int lcl_canplace(void);
static void lcl_spawn(void);
static int lcl_scanmatches(void);
static void lcl_applygravity(void);
static int lcl_resolve(void);
static void lcl_lockpiece(void);
static void lcl_newgame(void);
static void lcl_clearplane(void);
static void lcl_paintframe(void);
static void lcl__init(void);
static void lcl__update60(void);
static void lcl_paintboard(void);
static void lcl__draw(void);

int lcl_GW = 6;
int lcl_GH = 12;
int lcl_ITX = 14;
int lcl_ITY = 3;
int lcl_T_EMPTY = 0;
int lcl_T_WELL = 1;
int lcl_T_FRAME = 2;
int lcl_T_GEM0 = 3;
unsigned char lcl_grid[72];
unsigned char lcl_mask[72];
int lcl_px = 3;
int lcl_py = 0;
int lcl_c1 = 1;
int lcl_c2 = 2;
int lcl_c3 = 3;
int lcl_score = 0;
int lcl_level = 1;
int lcl_cleared = 0;
int lcl_fallt = 0;
int lcl_state = 0;
int lcl_flasht = 0;
int lcl_dirty = 1;
int lcl_seed = 137;
int lcl_qcol = 0;
int lcl_qrow = 0;

static int lcl_nextcolor(void)
{
    lcl_seed = ((((((lcl_seed) << 3) + ((lcl_seed) << 2) + (lcl_seed)) + 7)) % (251));
    return (((lcl_seed) % (5)) + 1);
}

static int lcl_canplace(void)
{
    if ((lcl_qcol < 0)) {
        return 0;
    }
    if (((lcl_qcol - (lcl_GW)) >= 0)) {
        return 0;
    }
    { unsigned char lcl_i = 0; unsigned char L_lim0 = 2;
        for (; lcl_i <= L_lim0; ++lcl_i) {
            { int lcl_ry = (lcl_qrow + lcl_i);
                if (((lcl_ry - (lcl_GH)) >= 0)) {
                    return 0;
                }
                if ((lcl_ry >= 0)) {
                    if (((unsigned char)lcl_grid[((lcl_ry * lcl_GW) + lcl_qcol)] != (unsigned char)0)) {
                        return 0;
                    }
                }
            }
        }
    }
    return 1;
}

static void lcl_spawn(void)
{
    lcl_px = 3;
    lcl_py = (-2);
    lcl_c1 = lcl_nextcolor();
    lcl_c2 = lcl_nextcolor();
    lcl_c3 = lcl_nextcolor();
    lcl_qcol = lcl_px;
    lcl_qrow = 0;
    if ((lcl_canplace() == 0)) {
        lcl_state = 1;
        md_music((-1), 1);
    }
}

static int lcl_scanmatches(void)
{
    { int lcl_i = 1; int L_lim1 = (lcl_GW * lcl_GH);
        for (; lcl_i <= L_lim1; ++lcl_i) {
            lcl_mask[lcl_i - 1] = 0;
        }
    }
    { int lcl_count = 0;
        { int lcl_row = 0; int L_lim2 = (lcl_GH - 1);
            for (; lcl_row <= L_lim2; ++lcl_row) {
                { int lcl_col = 0; int L_lim3 = (lcl_GW - 1);
                    for (; lcl_col <= L_lim3; ++lcl_col) {
                        { int lcl_v = lcl_grid[((lcl_row * lcl_GW) + lcl_col)];
                            if ((lcl_v != 0)) {
                                { unsigned char lcl_d = 0; unsigned char L_lim4 = 3;
                                    for (; lcl_d <= L_lim4; ++lcl_d) {
                                        { int lcl_dc = 0;
                                            { int lcl_dr = 0;
                                                if (((unsigned char)lcl_d == (unsigned char)0)) {
                                                    lcl_dc = 1;
                                                    lcl_dr = 0;
                                                }
                                                if (((unsigned char)lcl_d == (unsigned char)1)) {
                                                    lcl_dc = 0;
                                                    lcl_dr = 1;
                                                }
                                                if (((unsigned char)lcl_d == (unsigned char)2)) {
                                                    lcl_dc = 1;
                                                    lcl_dr = 1;
                                                }
                                                if (((unsigned char)lcl_d == (unsigned char)3)) {
                                                    lcl_dc = (-1);
                                                    lcl_dr = 1;
                                                }
                                                { int lcl_pc = (lcl_col - lcl_dc);
                                                    { int lcl_pr = (lcl_row - lcl_dr);
                                                        { int lcl_isstart = 1;
                                                            if (((((lcl_pc >= 0) && ((lcl_pc - (lcl_GW)) < 0)) && (lcl_pr >= 0)) && ((lcl_pr - (lcl_GH)) < 0))) {
                                                                if (((lcl_grid[((lcl_pr * lcl_GW) + lcl_pc)] - (lcl_v)) == 0)) {
                                                                    lcl_isstart = 0;
                                                                }
                                                            }
                                                            if ((lcl_isstart != 0)) {
                                                                { int lcl_len = 1;
                                                                    { int lcl_nc = (lcl_col + lcl_dc);
                                                                        { int lcl_nr = (lcl_row + lcl_dr);
                                                                            while ((((((lcl_nc >= 0) && ((lcl_nc - (lcl_GW)) < 0)) && (lcl_nr >= 0)) && ((lcl_nr - (lcl_GH)) < 0)) && ((lcl_grid[((lcl_nr * lcl_GW) + lcl_nc)] - (lcl_v)) == 0))) {
                                                                                lcl_len = (lcl_len + 1);
                                                                                lcl_nc = (lcl_nc + lcl_dc);
                                                                                lcl_nr = (lcl_nr + lcl_dr);
                                                                            }
                                                                            if ((lcl_len >= 3)) {
                                                                                { int lcl_mc = lcl_col;
                                                                                    { int lcl_mr = lcl_row;
                                                                                        { int lcl_k = 1; int L_lim5 = lcl_len;
                                                                                            for (; lcl_k <= L_lim5; ++lcl_k) {
                                                                                                { int lcl_idx = (((lcl_mr * lcl_GW) + lcl_mc) + 1);
                                                                                                    if (((unsigned char)lcl_mask[lcl_idx - 1] == (unsigned char)0)) {
                                                                                                        lcl_mask[lcl_idx - 1] = 1;
                                                                                                        lcl_count = (lcl_count + 1);
                                                                                                    }
                                                                                                    lcl_mc = (lcl_mc + lcl_dc);
                                                                                                    lcl_mr = (lcl_mr + lcl_dr);
                                                                                                }
                                                                                            }
                                                                                        }
                                                                                    }
                                                                                }
                                                                            }
                                                                        }
                                                                    }
                                                                }
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        return lcl_count;
    }
}

static void lcl_applygravity(void)
{
    { int lcl_col = 0; int L_lim6 = (lcl_GW - 1);
        for (; lcl_col <= L_lim6; ++lcl_col) {
            { int lcl_w = (lcl_GH - 1);
                { int lcl_row = (lcl_GH - 1); int L_lim7 = 0;
                    for (; lcl_row >= L_lim7; --lcl_row) {
                        { int lcl_v = lcl_grid[((lcl_row * lcl_GW) + lcl_col)];
                            if ((lcl_v != 0)) {
                                lcl_grid[((lcl_w * lcl_GW) + lcl_col)] = lcl_v;
                                lcl_w = (lcl_w - 1);
                            }
                        }
                    }
                }
                while ((lcl_w >= 0)) {
                    lcl_grid[((lcl_w * lcl_GW) + lcl_col)] = 0;
                    lcl_w = (lcl_w - 1);
                }
            }
        }
    }
}

static int lcl_resolve(void)
{
    { int lcl_chain = 0;
        { int lcl_n = lcl_scanmatches();
            while ((lcl_n > 0)) {
                lcl_chain = (lcl_chain + 1);
                { int lcl_i = 1; int L_lim8 = (lcl_GW * lcl_GH);
                    for (; lcl_i <= L_lim8; ++lcl_i) {
                        if (((unsigned char)lcl_mask[lcl_i - 1] != (unsigned char)0)) {
                            lcl_grid[lcl_i - 1] = 0;
                        }
                    }
                }
                { int lcl_amt = (((lcl_n) << 3) + ((lcl_n) << 1));
                    if ((lcl_chain > 1)) {
                        lcl_amt = (lcl_amt * lcl_chain);
                    }
                    lcl_score = (lcl_score + lcl_amt);
                    lcl_cleared = (lcl_cleared + lcl_n);
                    { int lcl_want = (((lcl_cleared) / (12)) + 1);
                        if ((lcl_want > 9)) {
                            lcl_want = 9;
                        }
                        lcl_level = lcl_want;
                        md_sfx((40 + (((lcl_chain) << 2))), -1);
                        lcl_applygravity();
                        lcl_n = lcl_scanmatches();
                    }
                }
            }
            return lcl_chain;
        }
    }
}

static void lcl_lockpiece(void)
{
    { unsigned char lcl_i = 0; unsigned char L_lim9 = 2;
        for (; lcl_i <= L_lim9; ++lcl_i) {
            { int lcl_ry = (lcl_py + lcl_i);
                { int lcl_col = 0;
                    if (((unsigned char)lcl_i == (unsigned char)0)) {
                        lcl_col = lcl_c1;
                    }
                    if (((unsigned char)lcl_i == (unsigned char)1)) {
                        lcl_col = lcl_c2;
                    }
                    if (((unsigned char)lcl_i == (unsigned char)2)) {
                        lcl_col = lcl_c3;
                    }
                    if ((lcl_ry >= 0)) {
                        lcl_grid[((lcl_ry * lcl_GW) + lcl_px)] = lcl_col;
                    }
                }
            }
        }
    }
    md_sfx(20, -1);
    lcl_dirty = 1;
    if ((lcl_py < 0)) {
        lcl_state = 1;
        md_music((-1), 1);
        return;
    }
    { int lcl_chain = lcl_resolve();
        if ((lcl_chain > 0)) {
            lcl_flasht = 8;
        }
        if ((lcl_state == 0)) {
            lcl_spawn();
        }
    }
}

static void lcl_newgame(void)
{
    { int lcl_i = 1; int L_lim10 = (lcl_GW * lcl_GH);
        for (; lcl_i <= L_lim10; ++lcl_i) {
            lcl_grid[lcl_i - 1] = 0;
        }
    }
    lcl_score = 0;
    lcl_level = 1;
    lcl_cleared = 0;
    lcl_fallt = 0;
    lcl_flasht = 0;
    lcl_state = 0;
    lcl_dirty = 1;
    lcl_spawn();
}

static void lcl_clearplane(void)
{
    { unsigned char lcl_r = 0; unsigned char L_lim11 = 27;
        for (; lcl_r <= L_lim11; ++lcl_r) {
            { unsigned char lcl_c = 0; unsigned char L_lim12 = 39;
                for (; lcl_c <= L_lim12; ++lcl_c) {
                    md_mset(0, lcl_c, lcl_r, lcl_T_EMPTY);
                }
            }
        }
    }
}

static void lcl_paintframe(void)
{
    { int lcl_x0 = (lcl_ITX - 1);
        { int lcl_x1 = (lcl_ITX + (((lcl_GW) << 1)));
            { int lcl_c = lcl_x0; int L_lim13 = lcl_x1;
                for (; lcl_c <= L_lim13; ++lcl_c) {
                    md_mset(0, lcl_c, (lcl_ITY - 1), lcl_T_FRAME);
                    md_mset(0, lcl_c, (lcl_ITY + (((lcl_GH) << 1))), lcl_T_FRAME);
                }
            }
            { int lcl_r = lcl_ITY; int L_lim14 = ((lcl_ITY + (((lcl_GH) << 1))) - 1);
                for (; lcl_r <= L_lim14; ++lcl_r) {
                    md_mset(0, (lcl_ITX - 1), lcl_r, lcl_T_FRAME);
                    md_mset(0, (lcl_ITX + (((lcl_GW) << 1))), lcl_r, lcl_T_FRAME);
                }
            }
        }
    }
}

static void lcl__init(void)
{
    md_map_show(0);
    md_music(0, 1);
    lcl_clearplane();
    lcl_paintframe();
    lcl_newgame();
}

static void lcl__update60(void)
{
    if ((lcl_state != 0)) {
        if (md_btnp(7, 0)) {
            md_music(0, 1);
            lcl_newgame();
        }
        return;
    }
    if ((lcl_flasht > 0)) {
        lcl_flasht = (lcl_flasht - 1);
    }
    lcl_qrow = lcl_py;
    if (md_btnp(0, 0)) {
        lcl_qcol = (lcl_px - 1);
        if ((lcl_canplace() != 0)) {
            lcl_px = (lcl_px - 1);
        }
    }
    if (md_btnp(1, 0)) {
        lcl_qcol = (lcl_px + 1);
        if ((lcl_canplace() != 0)) {
            lcl_px = (lcl_px + 1);
        }
    }
    if (md_btnp(4, 0)) {
        { int lcl_t = lcl_c3;
            lcl_c3 = lcl_c2;
            lcl_c2 = lcl_c1;
            lcl_c1 = lcl_t;
            md_sfx(30, -1);
        }
    }
    if (md_btnp(5, 0)) {
        lcl_qcol = lcl_px;
        lcl_qrow = (lcl_py + 1);
        while ((lcl_canplace() != 0)) {
            lcl_py = (lcl_py + 1);
            lcl_qrow = (lcl_py + 1);
        }
        lcl_lockpiece();
        return;
    }
    if (md_btn(3, 0)) {
        lcl_fallt = (lcl_fallt + 4);
    }
    lcl_fallt = (lcl_fallt + 1);
    { int lcl_delay = (33 - (((lcl_level) << 1) + (lcl_level)));
        if (((lcl_fallt - (lcl_delay)) >= 0)) {
            lcl_fallt = 0;
            lcl_qcol = lcl_px;
            lcl_qrow = (lcl_py + 1);
            if ((lcl_canplace() != 0)) {
                lcl_py = (lcl_py + 1);
            } else {
                lcl_lockpiece();
            }
        }
    }
}

static void lcl_paintboard(void)
{
    { int lcl_blink = 0;
        if (((lcl_flasht > 0) && ((lcl_flasht & 1) == 0))) {
            lcl_blink = 1;
        }
        { int lcl_row = 0; int L_lim15 = (lcl_GH - 1);
            for (; lcl_row <= L_lim15; ++lcl_row) {
                { int lcl_col = 0; int L_lim16 = (lcl_GW - 1);
                    for (; lcl_col <= L_lim16; ++lcl_col) {
                        { int lcl_v = lcl_grid[((lcl_row * lcl_GW) + lcl_col)];
                            if ((((lcl_v != 0) && (lcl_blink != 0)) && ((unsigned char)lcl_mask[((lcl_row * lcl_GW) + lcl_col)] != (unsigned char)0))) {
                                lcl_v = 0;
                            }
                            { int lcl_tx = (lcl_ITX + (((lcl_col) << 1)));
                                { int lcl_ty = (lcl_ITY + (((lcl_row) << 1)));
                                    if ((lcl_v == 0)) {
                                        md_mset(0, lcl_tx, lcl_ty, lcl_T_WELL);
                                        md_mset(0, (lcl_tx + 1), lcl_ty, lcl_T_WELL);
                                        md_mset(0, lcl_tx, (lcl_ty + 1), lcl_T_WELL);
                                        md_mset(0, (lcl_tx + 1), (lcl_ty + 1), lcl_T_WELL);
                                    } else {
                                        { int lcl_base = (lcl_T_GEM0 + ((((lcl_v - 1)) << 2)));
                                            md_mset(0, lcl_tx, lcl_ty, lcl_base);
                                            md_mset(0, (lcl_tx + 1), lcl_ty, (lcl_base + 1));
                                            md_mset(0, lcl_tx, (lcl_ty + 1), (lcl_base + 2));
                                            md_mset(0, (lcl_tx + 1), (lcl_ty + 1), (lcl_base + 3));
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

static void lcl__draw(void)
{
    md_print("gem well", 8, 8, 11);
    md_print("score", 8, 40, 7);
    md_print_int(lcl_score, 8, 52, 10);
    md_print("level", 8, 80, 7);
    md_print_int(lcl_level, 8, 92, 9);
    md_print("O cycle", 8, 176, 6);
    md_print("X drop", 8, 188, 6);
    if ((lcl_state != 0)) {
        md_print("GAME OVER", 232, 96, 8);
        md_print("press", 240, 120, 7);
        md_print("START", 240, 132, 12);
    } else {
        md_print("         ", 232, 96, 7);
        md_print("     ", 240, 120, 7);
        md_print("     ", 240, 132, 7);
    }
    if (((lcl_dirty != 0) || (lcl_flasht > 0))) {
        lcl_paintboard();
        lcl_dirty = 0;
    }
    if ((lcl_state == 0)) {
        { unsigned char lcl_i = 0; unsigned char L_lim17 = 2;
            for (; lcl_i <= L_lim17; ++lcl_i) {
                { int lcl_ry = (lcl_py + lcl_i);
                    if ((lcl_ry >= 0)) {
                        { int lcl_col = 0;
                            if (((unsigned char)lcl_i == (unsigned char)0)) {
                                lcl_col = lcl_c1;
                            }
                            if (((unsigned char)lcl_i == (unsigned char)1)) {
                                lcl_col = lcl_c2;
                            }
                            if (((unsigned char)lcl_i == (unsigned char)2)) {
                                lcl_col = lcl_c3;
                            }
                            { int lcl_sx = ((((lcl_ITX + (((lcl_px) << 1)))) << 3));
                                { int lcl_sy = ((((lcl_ITY + (((lcl_ry) << 1)))) << 3));
                                    md_spr(((((lcl_col - 1)) << 1)), lcl_sx, lcl_sy, 2, 2, 0 | (0 << 1));
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

int main(bool hard)
{
    (void)hard;
    md_init();
    lcl__init();
    for (;;) {
        md_vsync();
        lcl__update60();
        lcl__draw();
        md_endframe();
    }
    return 0;
}
