/* generated by mdlua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

const unsigned char lcl___p8map[20] = {
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
    0x01, 0x01, 0x01, 0x01
};
int lcl_ti = 0;
int lcl_wave = 2;

static void lcl__init(void)
{
    md_hud(2);
    md_music(0, 1);
    md_map(lcl___p8map, 128, 0, 0, 0, 32, 20, 1);
}

static void lcl__update60(void)
{
    lcl_ti = (lcl_ti + 1);
    if (md_btnp(4, 0)) {
        lcl_wave = (lcl_wave + 1);
    }
    if (md_btnp(5, 0)) {
        lcl_wave = (lcl_wave - 1);
    }
    lcl_wave = ((0 < lcl_wave) ? ((lcl_wave < 8) ? (lcl_wave) : (((unsigned char)0 < (unsigned char)8) ? (8) : (0))) : (((unsigned char)0 < (unsigned char)8) ? (0) : ((lcl_wave < 8) ? (8) : (lcl_wave))));
    { unsigned char lcl_line = 0; unsigned char L_lim0 = 223;
        for (; lcl_line <= L_lim0; ++lcl_line) {
            md_hscroll(lcl_line, (int)((md_fsin((((long)lcl_ti << 9) + ((long)lcl_line << 11))) * (((lcl_wave) << 1) + (lcl_wave))) >> 16));
        }
    }
    if ((((lcl_ti) % (6)) == 0)) {
        { int lcl_b = ((int)((long)((((long long)(((long)lcl_ti << 16))) << 16) / (393216L)) >> 16) & 3);
            md_pal(8, (8 + lcl_b));
            md_pal(10, (8 + ((lcl_b + 1) & 3)));
        }
    }
}

static void lcl__draw(void)
{
    md_cls(1);
    md_print("raster waves", 8, 0, 7);
    md_print_int(lcl_wave, 120, 0, 10);
    md_spr(0, 152, 104, 2, 2, 0 | (0 << 1));
}

int main(bool hard)
{
    (void)hard;
    md_init();
    lcl__init();
    for (;;) {
        md_vsync();
        lcl__update60();
        lcl__draw();
        md_endframe();
    }
    return 0;
}
