/* generated by mdlua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_ti = 0;

static void lcl__init(void)
{
    VDP_setTextPalette(0);
}

static void lcl__update60(void)
{
    lcl_ti = (lcl_ti + 1);
    PAL_setColor(15, VDP_getReg(0));
    if ((((lcl_ti) % (60)) == 0)) {
        VDP_setBackgroundColor(((int)((long)((((long long)(((long)lcl_ti << 16))) << 16) / (3932160L)) >> 16) & 7));
    }
}

static void lcl__draw(void)
{
    md_cls(1);
    VDP_drawText(0, 12, 4);
    md_print("+ pico-8 verbs", 8, 48, 10);
    md_print_int(lcl_ti, 8, 56, 7);
}

int main(bool hard)
{
    (void)hard;
    md_init();
    lcl__init();
    for (;;) {
        md_vsync();
        lcl__update60();
        lcl__draw();
        md_endframe();
    }
    return 0;
}
