/* generated by mdlua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void gtl__init(void);
static void gtl_fire(void);
static void gtl__update(void);
static void gtl__draw(void);

int gtl_px = 152;
int gtl_py = 194;
int gtl_pcool = 0;
int gtl_bx[8];
int gtl_by[8];
unsigned char gtl_ba[8];
int gtl_enx[12];
int gtl_eny[12];
unsigned char gtl_eal[12];
int gtl_edir = 1;
int gtl_edx = 0;
int gtl_alive = 12;
int gtl_lex = 0;
int gtl_ley = 0;
int gtl_let = 0;
int gtl_score = 0;
int gtl_lives = 3;
int gtl_state = 0;
int gtl_scrolly = 0;
int gtl_fadet = 0;
int gtl_endt = 0;

static void gtl__init(void)
{
    md_map_show(0);
    md_music(0, 1);
    { unsigned char gtl_i = 1; unsigned char L_lim0 = 12;
        for (; gtl_i <= L_lim0; ++gtl_i) {
            { int gtl_col = (((gtl_i - 1)) % (6));
                { int gtl_row = (((gtl_i - 1)) / (6));
                    gtl_enx[gtl_i - 1] = (40 + (((gtl_col) << 5) + ((gtl_col) << 3)));
                    gtl_eny[gtl_i - 1] = (28 + (((gtl_row) << 4) + ((gtl_row) << 3) + ((gtl_row) << 2)));
                    (gtl_eal - 1)[gtl_i] = 1;
                }
            }
        }
    }
    { unsigned char gtl_i = 1; unsigned char L_lim1 = 8;
        for (; gtl_i <= L_lim1; ++gtl_i) {
            (gtl_ba - 1)[gtl_i] = 0;
        }
    }
}

static void gtl_fire(void)
{
    { unsigned char gtl_i = 1; unsigned char L_lim2 = 8;
        for (; gtl_i <= L_lim2; ++gtl_i) {
            if (((unsigned char)(gtl_ba - 1)[gtl_i] == (unsigned char)0)) {
                gtl_bx[gtl_i - 1] = gtl_px;
                gtl_by[gtl_i - 1] = (gtl_py - 12);
                (gtl_ba - 1)[gtl_i] = 1;
                md_sfx(0, -1);
                return;
            }
        }
    }
}

static void gtl__update(void)
{
    if ((gtl_state != 0)) {
        if ((gtl_endt < 30)) {
            gtl_endt = (gtl_endt + 1);
        }
        md_fade((long)(((long long)((long)((((long long)(((long)gtl_endt << 16))) << 16) / (1966080L))) * (45875L /* 0.7 */)) >> 16), 0);
        if (md_btnp(4, 0)) {
            md_run();
        }
        return;
    }
    if ((gtl_fadet < 30)) {
        gtl_fadet = (gtl_fadet + 1);
        md_fade((65536L - (long)((((long long)(((long)gtl_fadet << 16))) << 16) / (1966080L))), 0);
    }
    gtl_scrolly = (gtl_scrolly + 1);
    VDP_setVerticalScroll(1, (-(gtl_scrolly >> 1)));
    if (md_btn(0, 0)) {
        gtl_px = (gtl_px - 3);
    }
    if (md_btn(1, 0)) {
        gtl_px = (gtl_px + 3);
    }
    if ((gtl_px < 4)) {
        gtl_px = 4;
    }
    if ((gtl_px > 300)) {
        gtl_px = 300;
    }
    if ((gtl_pcool > 0)) {
        gtl_pcool = (gtl_pcool - 1);
    }
    if ((md_btn(4, 0) && (gtl_pcool == 0))) {
        gtl_fire();
        gtl_pcool = 8;
    }
    { unsigned char gtl_i = 1; unsigned char L_lim3 = 8;
        for (; gtl_i <= L_lim3; ++gtl_i) {
            if (((unsigned char)(gtl_ba - 1)[gtl_i] != (unsigned char)0)) {
                gtl_by[gtl_i - 1] = ((gtl_by - 1)[gtl_i] - 6);
                if ((((gtl_by - 1)[gtl_i] - ((-16))) < 0)) {
                    (gtl_ba - 1)[gtl_i] = 0;
                }
            }
        }
    }
    gtl_edx = (gtl_edx + gtl_edir);
    if ((gtl_edx > 24)) {
        gtl_edir = (-1);
    }
    if (((gtl_edx - ((-24))) < 0)) {
        gtl_edir = 1;
    }
    if ((gtl_let > 0)) {
        gtl_let = (gtl_let - 1);
    }
    { unsigned char gtl_e = 1; unsigned char L_lim4 = 12;
        for (; gtl_e <= L_lim4; ++gtl_e) {
            if (((unsigned char)(gtl_eal - 1)[gtl_e] != (unsigned char)0)) {
                { int gtl_ex = ((gtl_enx - 1)[gtl_e] + gtl_edx);
                    { int gtl_ey = ((gtl_eny - 1)[gtl_e] + (gtl_scrolly >> 3));
                        if ((gtl_ey > 180)) {
                            gtl_state = 2;
                            md_music((-1), 1);
                            return;
                        }
                        { unsigned char gtl_i = 1; unsigned char L_lim5 = 8;
                            for (; gtl_i <= L_lim5; ++gtl_i) {
                                if (((unsigned char)(gtl_ba - 1)[gtl_i] != (unsigned char)0)) {
                                    { int gtl_dx = ((gtl_bx - 1)[gtl_i] - gtl_ex);
                                        { int gtl_dy = ((gtl_by - 1)[gtl_i] - gtl_ey);
                                            if ((((((gtl_dx - ((-12))) > 0) && (gtl_dx < 12)) && ((gtl_dy - ((-12))) > 0)) && (gtl_dy < 12))) {
                                                (gtl_eal - 1)[gtl_e] = 0;
                                                (gtl_ba - 1)[gtl_i] = 0;
                                                gtl_score = (gtl_score + 10);
                                                gtl_alive = (gtl_alive - 1);
                                                gtl_lex = gtl_ex;
                                                gtl_ley = gtl_ey;
                                                gtl_let = 12;
                                                md_sfx(0, -1);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
    if ((gtl_alive <= 0)) {
        gtl_state = 1;
        md_music((-1), 1);
    }
}

static void gtl__draw(void)
{
    if ((gtl_state == 1)) {
        md_print("YOU WIN!", 128, 90, 11);
        md_print("score", 128, 110, 7);
        md_print_int(gtl_score, 176, 110, 10);
        md_print("press O", 132, 130, 12);
        return;
    }
    if ((gtl_state == 2)) {
        md_print("GAME OVER", 124, 90, 8);
        md_print("score", 128, 110, 7);
        md_print_int(gtl_score, 176, 110, 10);
        md_print("press O", 132, 130, 12);
        return;
    }
    md_print("score", 4, 4, 7);
    md_print_int(gtl_score, 44, 4, 10);
    md_print("lives", 250, 4, 7);
    md_print_int(gtl_lives, 290, 4, 8);
    md_spr(0, gtl_px, gtl_py, 2, 2, 0 | (0 << 1));
    { unsigned char gtl_i = 1; unsigned char L_lim6 = 8;
        for (; gtl_i <= L_lim6; ++gtl_i) {
            if (((unsigned char)(gtl_ba - 1)[gtl_i] != (unsigned char)0)) {
                md_spr(6, (gtl_bx - 1)[gtl_i], (gtl_by - 1)[gtl_i], 2, 2, 0 | (0 << 1));
            }
        }
    }
    { unsigned char gtl_e = 1; unsigned char L_lim7 = 12;
        for (; gtl_e <= L_lim7; ++gtl_e) {
            if (((unsigned char)(gtl_eal - 1)[gtl_e] != (unsigned char)0)) {
                md_spr(2, ((gtl_enx - 1)[gtl_e] + gtl_edx), ((gtl_eny - 1)[gtl_e] + (gtl_scrolly >> 3)), 2, 2, 0 | (0 << 1));
            }
        }
    }
    if ((gtl_let > 0)) {
        md_spr(4, gtl_lex, gtl_ley, 2, 2, 0 | (0 << 1));
    }
}

int main(bool hard)
{
    (void)hard;
    md_init();
    gtl__init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            gtl__update();
        }
        _md_odd ^= 1;
        gtl__draw();
        md_endframe();
    }
    return 0;
}
