/* generated by mdlua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl_on_frame_change(void);
static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_hits[2];
int lcl_frames = 0;
int lcl_spr = 0;

static void lcl_on_frame_change(void)
{
    lcl_hits[-1] = (lcl_hits[-1] + 1);
}

static void lcl__init(void)
{
    lcl_hits[-1] = 0;
    SPR_init();
    lcl_spr = (int)SPR_addSprite((void*)(md_demo_sprite()), 120, 100, 0);
    SPR_setFrameChangeCallback((void*)(lcl_spr), (void*)&lcl_on_frame_change);
    SPR_setAnim((void*)(lcl_spr), 0);
    SPR_setAutoAnimation((void*)(lcl_spr), ((1) ? 1 : 0));
}

static void lcl__update60(void)
{
    lcl_frames = (lcl_frames + 1);
}

static void lcl__draw(void)
{
    md_print("sprite callback", 8, 8, 7);
    md_print("hits:", 8, 28, 6);
    md_print_int(lcl_hits[-1], 56, 28, 11);
    md_print("frame:", 8, 40, 6);
    md_print_int(lcl_frames, 56, 40, 10);
}

int main(bool hard)
{
    (void)hard;
    md_init();
    lcl__init();
    for (;;) {
        md_vsync();
        lcl__update60();
        lcl__draw();
        md_endframe();
    }
    return 0;
}
