/* generated by mdlua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl_on_vblank(void);
static void lcl__init(void);
static void lcl__update60(void);
static void lcl__draw(void);

int lcl_vints[2];
int lcl_frames = 0;

static void lcl_on_vblank(void)
{
    lcl_vints[-1] = (lcl_vints[-1] + 1);
}

static void lcl__init(void)
{
    lcl_vints[-1] = 0;
    SYS_setVIntCallback((void*)&lcl_on_vblank);
}

static void lcl__update60(void)
{
    lcl_frames = (lcl_frames + 1);
}

static void lcl__draw(void)
{
    md_cls(1);
    md_print("vint callback", 8, 8, 7);
    md_print("vints:", 8, 28, 6);
    md_print_int(lcl_vints[-1], 64, 28, 11);
    md_print("frame:", 8, 40, 6);
    md_print_int(lcl_frames, 64, 40, 10);
}

int main(bool hard)
{
    (void)hard;
    md_init();
    lcl__init();
    for (;;) {
        md_vsync();
        lcl__update60();
        lcl__draw();
        md_endframe();
    }
    return 0;
}
