/* generated by mdlua from synth-fixedmath.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl__update(void);
static void lcl__draw(void);

long lcl_x = 0L; /* 0 */

static void lcl__update(void)
{
    lcl_x = (lcl_x + 32768L /* 0.5 */);
    lcl_x = ((lcl_x) + ((lcl_x) >> 1));
    lcl_x = (long)((((long long)(lcl_x)) << 16) / (196608L));
}

static void lcl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            lcl__update();
        }
        _md_odd ^= 1;
        lcl__draw();
        md_endframe();
    }
    return 0;
}
