/* generated by mdlua from synth-btn.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    if (md_btn(0, 0)) {
    }
    if (md_btnp(4, 0)) {
    }
}

static void lcl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            lcl__update();
        }
        _md_odd ^= 1;
        lcl__draw();
        md_endframe();
    }
    return 0;
}
