/* generated by mdlua from synth-shapes.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl__draw(void);

static void lcl__draw(void)
{
    md_cls(1);
    md_rectfill(4, 4, 20, 20, 8);
    md_circfill(64, 64, 10, 10);
    md_line(0, 0, 127, 127, 7);
    md_spr(0, 10, 10, 1, 1, 0 | (0 << 1));
    md_print("hi", 4, 4, 7);
}

int main(bool hard)
{
    (void)hard;
    md_init();
    for (;;) {
        md_vsync();
        lcl__draw();
        md_endframe();
    }
    return 0;
}
