/* generated by mdlua from synth-array.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void gtl__update(void);
static void gtl__draw(void);

int gtl_a[16];
unsigned char gtl_b[8];

static void gtl__update(void)
{
    gtl_a[0] = 5;
    gtl_b[0] = 2;
}

static void gtl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            gtl__update();
        }
        _md_odd ^= 1;
        gtl__draw();
        md_endframe();
    }
    return 0;
}
