/* generated by mdlua from synth-func.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static int lcl_helper(int lcl_x, int lcl_y);
static void lcl__update(void);
static void lcl__draw(void);

static int lcl_helper(int lcl_x, int lcl_y)
{
    return (lcl_x + lcl_y);
}

static void lcl__update(void)
{
    { int lcl_z = (((1) + (2)));
    }
}

static void lcl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            lcl__update();
        }
        _md_odd ^= 1;
        lcl__draw();
        md_endframe();
    }
    return 0;
}
