/* generated by mdlua from synth-fornum.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    { int lcl_i = 0; int L_lim0 = 255;
        for (; lcl_i <= L_lim0; ++lcl_i) {
        }
    }
    { int lcl_j = 1; int L_lim1 = 10;
        for (; lcl_j <= L_lim1; lcl_j += 2) {
        }
    }
}

static void lcl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            lcl__update();
        }
        _md_odd ^= 1;
        lcl__draw();
        md_endframe();
    }
    return 0;
}
