/* generated by gbalua from synth-fornum.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    { int gtl_i = 0; int L_lim0 = 255;
        for (; gtl_i <= L_lim0; ++gtl_i) {
        }
    }
    { int gtl_j = 1; int L_lim1 = 10;
        for (; gtl_j <= L_lim1; gtl_j += 2) {
        }
    }
}

static void gtl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            gtl__update();
        }
        _md_odd ^= 1;
        gtl__draw();
        md_endframe();
    }
    return 0;
}
