/* generated by mdlua from synth-minmax.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void lcl__update(void);
static void lcl__draw(void);

static void lcl__update(void)
{
    { int lcl_a = (((unsigned char)1 < (unsigned char)2) ? (1) : (2));
        { int lcl_b = (((unsigned char)3 > (unsigned char)4) ? (3) : (4));
            { int lcl_c = (((unsigned char)1 < (unsigned char)2) ? (((unsigned char)2 < (unsigned char)3) ? (2) : (((unsigned char)1 < (unsigned char)3) ? (3) : (1))) : (((unsigned char)1 < (unsigned char)3) ? (1) : (((unsigned char)2 < (unsigned char)3) ? (3) : (2))));
                { int lcl_d = md_absi((-5));
                }
            }
        }
    }
}

static void lcl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            lcl__update();
        }
        _md_odd ^= 1;
        lcl__draw();
        md_endframe();
    }
    return 0;
}
