/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void gtl__init(void);
static void gtl__update(void);
static void gtl__draw(void);

static void gtl__init(void)
{
    md_map_show(0);
}

static void gtl__update(void)
{
    if (md_btnp(4, 0)) {
        md_anim_reset(2);
    }
}

static void gtl__draw(void)
{
    md_print("animation helpers", 96, 20, 7);
    md_print("loop", 72, 80, 6);
    md_print("pong", 152, 80, 6);
    md_print("once", 232, 80, 6);
    md_print("press O to replay", 100, 180, 5);
    md_spr(md_anim(0, 0, 3, 655360L), 72, 104, 2, 2, 0 | (0 << 1));
    md_spr(md_anim_pingpong(1, 0, 3, 524288L), 152, 104, 2, 2, 0 | (0 << 1));
    md_spr(md_anim_once(2, 0, 3, 393216L), 232, 104, 2, 2, 0 | (0 << 1));
    if ((md_anim_done(2) != 0)) {
        md_print("done", 232, 136, 11);
    }
}

int main(bool hard)
{
    (void)hard;
    md_init();
    gtl__init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            gtl__update();
        }
        _md_odd ^= 1;
        gtl__draw();
        md_endframe();
    }
    return 0;
}
