/* generated by gbalua from main.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void gtl__init(void);
static void gtl__update60(void);
static void gtl__draw(void);

const unsigned char gtl___p8map[20] = {
    0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01, 0x01,
    0x01, 0x01, 0x01, 0x01
};
int gtl_ti = 0;
int gtl_wave = 2;

static void gtl__init(void)
{
    md_hud(2);
    md_music(0, 1);
    md_map(gtl___p8map, 128, 0, 0, 0, 32, 20, 1);
}

static void gtl__update60(void)
{
    gtl_ti = (gtl_ti + 1);
    if (md_btnp(4, 0)) {
        gtl_wave = (gtl_wave + 1);
    }
    if (md_btnp(5, 0)) {
        gtl_wave = (gtl_wave - 1);
    }
    gtl_wave = ((0 < gtl_wave) ? ((gtl_wave < 8) ? (gtl_wave) : (((unsigned char)0 < (unsigned char)8) ? (8) : (0))) : (((unsigned char)0 < (unsigned char)8) ? (0) : ((gtl_wave < 8) ? (8) : (gtl_wave))));
    { unsigned char gtl_line = 0; unsigned char L_lim0 = 223;
        for (; gtl_line <= L_lim0; ++gtl_line) {
            md_hscroll(gtl_line, (int)((md_fsin((((long)gtl_ti << 9) + ((long)gtl_line << 11))) * (((gtl_wave) << 1) + (gtl_wave))) >> 16));
        }
    }
    if ((((gtl_ti) % (6)) == 0)) {
        { int gtl_b = ((int)((long)((((long long)(((long)gtl_ti << 16))) << 16) / (393216L)) >> 16) & 3);
            md_pal(8, (8 + gtl_b));
            md_pal(10, (8 + ((gtl_b + 1) & 3)));
        }
    }
}

static void gtl__draw(void)
{
    md_cls(1);
    md_print("raster waves", 8, 0, 7);
    md_print_int(gtl_wave, 120, 0, 10);
    md_spr(0, 152, 104, 2, 2, 0 | (0 << 1));
}

int main(bool hard)
{
    (void)hard;
    md_init();
    gtl__init();
    for (;;) {
        md_vsync();
        gtl__update60();
        gtl__draw();
        md_endframe();
    }
    return 0;
}
