/* generated by gbalua from synth-func.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static int gtl_helper(int gtl_x, int gtl_y);
static void gtl__update(void);
static void gtl__draw(void);

static int gtl_helper(int gtl_x, int gtl_y)
{
    return (gtl_x + gtl_y);
}

static void gtl__update(void)
{
    { int gtl_z = (((1) + (2)));
    }
}

static void gtl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            gtl__update();
        }
        _md_odd ^= 1;
        gtl__draw();
        md_endframe();
    }
    return 0;
}
