/* generated by gbalua from synth-minmax.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void gtl__update(void);
static void gtl__draw(void);

static void gtl__update(void)
{
    { int gtl_a = (((unsigned char)1 < (unsigned char)2) ? (1) : (2));
        { int gtl_b = (((unsigned char)3 > (unsigned char)4) ? (3) : (4));
            { int gtl_c = (((unsigned char)1 < (unsigned char)2) ? (((unsigned char)2 < (unsigned char)3) ? (2) : (((unsigned char)1 < (unsigned char)3) ? (3) : (1))) : (((unsigned char)1 < (unsigned char)3) ? (1) : (((unsigned char)2 < (unsigned char)3) ? (3) : (2))));
                { int gtl_d = md_absi((-5));
                }
            }
        }
    }
}

static void gtl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            gtl__update();
        }
        _md_odd ^= 1;
        gtl__draw();
        md_endframe();
    }
    return 0;
}
