/* generated by gbalua from synth-fixedmath.lua - edit the .lua, not this file */
#include "md_api.h"
#include "md_math.h"

static void gtl__update(void);
static void gtl__draw(void);

long gtl_x = 0L; /* 0 */

static void gtl__update(void)
{
    gtl_x = (gtl_x + 32768L /* 0.5 */);
    gtl_x = ((gtl_x) + ((gtl_x) >> 1));
    gtl_x = (long)((((long long)(gtl_x)) << 16) / (196608L));
}

static void gtl__draw(void)
{
}

int main(bool hard)
{
    (void)hard;
    md_init();
    unsigned char _md_odd = 0;
    for (;;) {
        md_vsync();
        if (_md_odd == 0) {
            gtl__update();
        }
        _md_odd ^= 1;
        gtl__draw();
        md_endframe();
    }
    return 0;
}
