// GENERATED by tools/gen-sgdk-builtins.mjs — do not edit by hand.
// The direct-call SGDK surface: every scalar/pointer-handle SGDK function
// exposed under its own name. Curated PICO-8 verbs (builtins.js) win name
// clashes. C names are raw SGDK symbols (no gt_ root -> the emitter's remap
// leaves them alone -> they link straight to the bundled libmd.
// 0 functions. Regenerate: node tools/gen-sgdk-builtins.mjs
export const SGDK_BUILTINS = {

};
